---
name: Codespell

on:
  pull_request:
  push:

jobs:
  codespell:
    name: Check for spelling errors
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: codespell-project/actions-codespell@v1
        with:
          skip: ./po/de.po,./po/fr.po,./po/nl.po,./po/pt_BR.po
          ignore_words_file: codespell_ignore_words.txt
